### ISSUE TITLE
Initialize plugin repository

### ISSUE THREAD

**Issue by abraham-kaczmarski** [Justyanna/toy-box#8]
Bootsrap a functioning plugin repository with slots for essential features.

## Todo

- [ ] Plan out the repository structure
- [ ] Bootstrap plugin logic (backend) validation flow
- [ ] Bootsrtap plugin components (frontend) validation flow
- [ ] Document the plugin access flow
- [ ] Create a simplified demo
